### PR TITLE
Fix perpetual state update in task form

### PR DESCRIPTION
**Pull request by jadmnsaad**
https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/1724

Details:
- remove unnecessary logic and refs
- refactor how number of days and end date are updated

### CODE REVIEW

**Comment by dinesh-aot** [comment]
image
Could you please handle this

**Review by dinesh-aot — APPROVED** [review]

**Comment by jadmnsaad** [comment]
> image Could you please handle this

is this happening with the changes in this PR or this is what is happening currently before this merge.

Because I handled this issue in this PR, is it still happening despite these changes?

**Comment by dinesh-aot** [comment]
> > image Could you please handle this
> 
> is this happening with the changes in this PR or this is what is happening currently before this merge.
> 
> Because I handled this issue in this PR, is it still happening despite these changes?

I had checked out this PR yesterday in local and saw this happening

**Comment by jadmnsaad** [comment]
> > > image Could you please handle this
> > 
> > 
> > is this happening with the changes in this PR or this is what is happening currently before this merge.
> > Because I handled this issue in this PR, is it still happening despite these changes?
> 
> I had checked out this PR yesterday in local and saw this happening

I rechecked and it's not happening on my local. There's a chance you might of tested my code before I committed that fix. I will merge this

**Pull request merged**
