### PR TITLE
Fix issue buttons

### PR DESCRIPTION
**Pull request by djnunez-aot**
#1175 

-Fix inconsistent padding toggling between buttons in workplan issues tab

### CODE REVIEW

**Comment by jadmnsaad** [comment]
Fixing inconsistent padding by changing colors? Is there another way?

**Comment by djnunez-aot** [comment]
> Fixing inconsistent padding by changing colors? Is there another way?
@jadmsaadaot the problem is  we swap from an outlined button to a contained button on press originally and they have different styling. Maybe we could create a custom component and it does all that logic handling for us but i don't know if that's valuable

**Comment by jadmnsaad** [comment]
> > Fixing inconsistent padding by changing colors? Is there another way?
> > @jadmsaadaot the problem is  we swap from an outlined button to a contained button on press originally and they have different styling. Maybe we could create a custom component and it does all that logic handling for us but i don't know if that's valuable

We should ideally stay away from spot changes to colors for atomic components like Buttons. We could perhaps update the styling in the theme. If we created a custom component for button we should probably use it everywhere. Or maybe just a spot change to the padding could be okay.

**Comment by djnunez-aot** [comment]
> > > Fixing inconsistent padding by changing colors? Is there another way?
> > > @jadmsaadaot the problem is  we swap from an outlined button to a contained button on press originally and they have different styling. Maybe we could create a custom component and it does all that logic handling for us but i don't know if that's valuable
> 
> We should ideally stay away from spot changes to colors for atomic components like Buttons. We could perhaps update the styling in the theme. If we created a custom component for button we should probably use it everywhere. Or maybe just a spot change to the padding could be okay.

sounds good ill change the solution to do that instead then ill try to add a common component for this

**Review by jadmnsaad — APPROVED** [review]

**Pull request merged**
